name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  vulnerabilityTest:
    runs-on: ubuntu-latest
    name: vulnerabilityTest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: ' ${{ runner.temp }}'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js version 16

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Check Node.js Version
        run: node -v

      - name: Convert HTML to Image
        run: node ./convert-html-to-image.js

      - name: Copy Reports to Workspace
        run: cp ${{ runner.temp }}/reports/dependency-check-report.png ./reports

      - name: Upload Test results
        uses: actions/upload-artifact@v2
        with:
          name: Depcheck report
          path: reports

      - name: Deploy to GitHub Pages
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cp reports/dependency-check-report.png gh-pages/
          cd gh-pages
          git add dependency-check-report.png
          git commit -m "Update dependency check report image"
          git push
